#define SERVER_NAME         "Jogjagamers Gangwar"
#define SERVER_NAME_SHORT   "JG:GW"
#define GAMEMODE_VERSION    "0.1a Alpha"

#define MYSQL_HOST          "localhost"
#define MYSQL_USER          "gta5"
#define MYSQL_DATABASE      "gta_gangwar"
#define MYSQL_PASSWORD      ""

#define MAX_GANGS           5
#define MAX_GANG_NAME       32

#define JOB_HEALER      	1
#define JOB_DEALER_ARMS     2
#define JOB_DEALER_DRUG     4
#define JOB_MECHANIC        8

#define DIALOG_USER_REGISTER        1
#define DIALOG_USER_LOGIN           2
